apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wasmcloud-secrets-reader-default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wasmcloud-secrets-reader-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wasmcloud-secrets-reader-default
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "system:serviceaccount:wasmcloud-secrets:default"
