apiVersion: v1
kind: Service
metadata:
  name: {{ include "wasmcloud-secrets-vault.fullname" . }}
  labels:
    {{- include "wasmcloud-secrets-vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: jwks-endpoint
      protocol: TCP
      name: jwks-endpoint
  selector:
    {{- include "wasmcloud-secrets-vault.selectorLabels" . | nindent 4 }}
