apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wasmcloud-secrets
  name: wasmcloud-secrets
spec:
  selector:
    matchLabels:
      app: wasmcloud-secrets
  template:
    metadata:
      labels:
        app: wasmcloud-secrets
    spec:
      containers:
        - image: wasmcloud-secrets
          imagePullPolicy: IfNotPresent
          name: wasmcloud-secrets
