apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../impersonation/

images:
  - name: wasmcloud-secrets
    newName: ghcr.io/wasmcloud/contrib/secrets-kubernetes
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/args"
        value:
          - "--backend-seed=SXAD2NAUWO6YNEFMY4FQT7D45VLLWFOZDVHCENMPHCWA6ABBLZ4OBBKGKQ"
          - "--nats-url=nats.default.svc.cluster.local:4222"
    target:
      kind: Deployment
      namespace: wasmcloud-secrets
      name: wasmcloud-secrets
