name: Secrets Vault

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wasmcloud/contrib/secrets-vault

defaults:
  run:
    shell: bash
    working-directory: ./secrets/secrets-vault

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          cargo clippy -- --no-deps

      - name: Test
        run: |
          cargo test

      - name: Build
        run: |
          cargo build --release

  release:
    if: startswith(github.ref, 'refs/tags/secrets-vault-v') # Only run on tag push
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta_release
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=secrets-vault-v(.*),group=1

      - name: Extract metadata (tags, labels)
        id: meta_debug
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=secrets-vault-v(.*),group=1,suffix=-debug

      - name: Build and push the release image
        uses: docker/build-push-action@v6
        with:
          target: release
          push: true
          context: secrets/secrets-vault/
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push the debug image
        uses: docker/build-push-action@v6
        with:
          target: debug
          push: true
          context: secrets/secrets-vault/
          tags: ${{ steps.meta_debug.outputs.tags }}
          labels: ${{ steps.meta_debug.outputs.labels }}
          platforms: linux/amd64,linux/arm64